---
- name: install a bunch of system packages on which LMS and CMS rely
  apt: pkg={{','.join(lms_debian_pkgs)}} state=present

#- include: lms.yml
#  when: "'lms' in service_variants_enabled"
#- include: cms.yml
#  when: "'cms' in service_variants_enabled"

#- name: creating edxapp upstart script
#  template: src=edxapp.conf.j2 dest=/etc/init/edxapp.conf owner=root group=root

- include: npm.yml
- include: ruby.yml

#- name: stop edxapp services
#  service: name=edxapp state=stopped

- name: vagrant | check if edx-platform repository directory is mounted
  command: grep {{edx_platform_code_dir}} /proc/mounts
  register: platform_mount
  ignore_errors: yes

- name: git checkout edx-platform repo into $app_base_dir
  git: dest={{edx_platform_code_dir}} repo={{lms_source_repo}} version={{lms_version}}
  when_failed: $platform_mount

- name: sets permissions on platform code dir and contents
  file: path={{edx_platform_code_dir}} state=directory owner=www-data group=www-data recurse=yes
  when_failed: $platform_mount

- include: dependencies_update.yml

- name: syncdb and migrate
  shell: sudo -u www-data SERVICE_VARIANT=lms /opt/edx/bin/django-admin.py syncdb --migrate --noinput --settings=cms.envs.dev --pythonpath=/opt/wwc/edx-platform

#- name: restart edxapp
#  service: name=edxapp state=restarted
