---
- name: install a bunch of system packages on which LMS and CMS rely
  apt: pkg={{','.join(lms_debian_pkgs)}} state=present

#- include: lms.yml
#- include: cms.yml

#- name: creating edxapp upstart script
#  template: src=edxapp.conf.j2 dest=/etc/init/edxapp.conf owner=root group=root

- include: npm.yml
- include: ruby.yml

- name: git checkout edx-platform repo into $app_base_dir
  git: dest={{edx_platform_code_dir}} repo={{lms_source_repo}} version={{lms_version}}
  when: "'/vagrant' not in [ m['mount'] for m in ansible_mounts ]"

- include: dependencies_update.yml


