- name: Configure instance(s)
  hosts: jenkins
  sudo: True
  gather_facts: True
  vars_files:
    - "{{ secure_dir }}/vars/edxapp_ref_users.yml"
    - "{{ secure_dir }}/vars/edxapp_sandbox.yml"
    - "vars/jenkins.yml"
  roles:
    - common
    - edxlocal
    - jenkins
