- name: Configure development instance
  hosts: vagrant
  sudo: True
  gather_facts: True
  vars:
    migrate_db: "yes"
    openid_workaround: True
  roles:
    - common
    - nginx
    - edxlocal
    - edxappdev
