- name: Configure development instance
  hosts: vagrant
  sudo: True
  gather_facts: True
  vars:
    migrate_db: "yes"
    openid_workaround: True
  roles:
    - common
    - nginx
    - edxlocal
    - edxappdev
    - oraclejdk
    - elasticsearch
    - role: rbenv
      rbenv_user: "{{ forum_user }}"
      rbenv_user_home: "{{ forum_home }}"
      rbenv_ruby_version: "{{ forum_ruby_version }}"
    - forum

