- name: Configure instance(s)
  hosts: vagrant
  sudo: True
  gather_facts: True
  vars:
    migrate_db: "yes"
    openid_workaround: True
  roles:
    - common
    - nginx
    - edxlocal
    - edxapp
    - rabbitmq
    - xqueue
    - xserver
    - { role: 'edxapp', celery_worker: True }
