# -*- mode: ruby -*-
# vi: set ft=ruby :
MEMORY = 1024
CPU_COUNT = 2

Vagrant.configure("2") do |config|
  config.vm.box     = "precise32"
  config.vm.box_url = "http://files.vagrantup.com/precise32.box"

  config.vm.network :private_network, ip: "192.168.33.10"

  config.vm.provider :virtualbox do |vb|
    vb.customize ["modifyvm", :id, "--memory", MEMORY.to_s]
    vb.customize ["modifyvm", :id, "--cpus", CPU_COUNT.to_s]
  end

  config.vm.provision :ansible do |ansible|
    ansible.playbook = "../../playbooks/vagrant-dev.yml"

    ansible.inventory_file = "../../playbooks/inventory_vagrant.ini"
    ansible.extra_vars = { secure_dir: "secure_example" }
    ansible.verbose = true
  end
end
